on: [push, pull_request]

name: Build/test taglogic

jobs:
  test:
    name: taglogic tests (no WASM)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo test
        run: cargo test
        working-directory: taglogic

  formatted:
    name: Formatted with rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: taglogic
  min-vers:
    name: works with minimal dependency versions
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Set versions to minimal
      # only direct deps, since ancient transitive deps (e.g. proc-macro2) don't build on current nightly
      run: cargo update -Z direct-minimal-versions
      working-directory: taglogic

    - name: Run cargo test
      run: cargo test
      working-directory: taglogic
